# Generated by Django 3.2.5 on 2021-10-18 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('date', models.DateField()),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasktype')),
            ],
        ),
    ]
